
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.14.0
 * Query Engine version: 717184b7b35ea05dfa71a3236b7af656013e1e49
 */
Prisma.prismaVersion = {
  client: "6.14.0",
  engine: "717184b7b35ea05dfa71a3236b7af656013e1e49"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.BranchesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  status: 'status',
  director_id: 'director_id',
  region: 'region',
  address: 'address',
  bank_name: 'bank_name',
  bank_account: 'bank_account',
  inn: 'inn',
  mfo: 'mfo',
  added_at: 'added_at',
  added_by: 'added_by'
};

exports.Prisma.DepartmentsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  status: 'status',
  branch_id: 'branch_id',
  added_at: 'added_at'
};

exports.Prisma.Employment_ordersScalarFieldEnum = {
  id: 'id',
  employee_id: 'employee_id',
  type: 'type',
  date: 'date',
  branch_id: 'branch_id',
  department_id: 'department_id',
  position_id: 'position_id',
  order_number: 'order_number',
  note: 'note',
  added_at: 'added_at'
};

exports.Prisma.EmployeesScalarFieldEnum = {
  id: 'id',
  employee_number: 'employee_number',
  last_name: 'last_name',
  first_name: 'first_name',
  middle_name: 'middle_name',
  date_of_birth: 'date_of_birth',
  gender: 'gender',
  passport: 'passport',
  passport_expiry_date: 'passport_expiry_date',
  pinfl: 'pinfl',
  education: 'education',
  phone: 'phone',
  email: 'email',
  address: 'address',
  status: 'status',
  photo: 'photo',
  branch_id: 'branch_id',
  department_id: 'department_id',
  position_id: 'position_id',
  work_schedule_id: 'work_schedule_id',
  education_specialty: 'education_specialty',
  added_at: 'added_at',
  updated_at: 'updated_at'
};

exports.Prisma.Face_passesScalarFieldEnum = {
  id: 'id',
  date: 'date',
  identifier: 'identifier',
  photo: 'photo',
  employee_id: 'employee_id',
  door_id: 'door_id',
  face_devices_id: 'face_devices_id',
  direction: 'direction',
  added_at: 'added_at'
};

exports.Prisma.HolidaysScalarFieldEnum = {
  id: 'id',
  name: 'name',
  date_from: 'date_from',
  date_to: 'date_to',
  added_by: 'added_by',
  added_at: 'added_at'
};

exports.Prisma.PositionsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  status: 'status',
  added_at: 'added_at'
};

exports.Prisma.SessionsScalarFieldEnum = {
  id: 'id',
  refresh_token: 'refresh_token',
  ip_address: 'ip_address',
  user_agent: 'user_agent',
  added_at: 'added_at',
  expires_at: 'expires_at',
  user_id: 'user_id'
};

exports.Prisma.Telegram_botsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  chat_id: 'chat_id',
  selectedEmployeeIds: 'selectedEmployeeIds',
  receive_late_report: 'receive_late_report',
  receive_event_alerts: 'receive_event_alerts',
  receive_attendance_report: 'receive_attendance_report',
  status: 'status',
  added_at: 'added_at'
};

exports.Prisma.Time_offScalarFieldEnum = {
  id: 'id',
  employee_id: 'employee_id',
  reason: 'reason',
  date_from: 'date_from',
  date_to: 'date_to',
  added_by: 'added_by',
  added_at: 'added_at',
  is_company_paid: 'is_company_paid',
  type: 'type',
  credited_hours: 'credited_hours'
};

exports.Prisma.TimesheetScalarFieldEnum = {
  id: 'id',
  month: 'month',
  year: 'year',
  day: 'day',
  worked_hours: 'worked_hours',
  intervals: 'intervals',
  user_id: 'user_id'
};

exports.Prisma.UsersScalarFieldEnum = {
  id: 'id',
  username: 'username',
  password: 'password',
  telegram_id: 'telegram_id',
  employee_id: 'employee_id',
  status: 'status',
  access_level: 'access_level',
  branch_access: 'branch_access',
  department_access: 'department_access',
  language: 'language',
  theme: 'theme',
  sidebar: 'sidebar',
  view_mode: 'view_mode',
  personal_menus: 'personal_menus',
  active_branch_id: 'active_branch_id',
  added_at: 'added_at'
};

exports.Prisma.MenusScalarFieldEnum = {
  id: 'id',
  name: 'name',
  path: 'path',
  parent_id: 'parent_id',
  sort_order: 'sort_order'
};

exports.Prisma.User_menu_accessScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  menu_id: 'menu_id',
  can_view: 'can_view',
  can_add: 'can_add',
  can_update: 'can_update',
  can_delete: 'can_delete'
};

exports.Prisma.Work_schedulesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  weekly_days: 'weekly_days',
  weekly_hours: 'weekly_hours',
  work_days: 'work_days',
  shifts: 'shifts',
  added_at: 'added_at',
  status: 'status'
};

exports.Prisma.Employee_schedule_historyScalarFieldEnum = {
  id: 'id',
  employee_id: 'employee_id',
  work_schedule_id: 'work_schedule_id',
  date_from: 'date_from',
  date_to: 'date_to',
  added_at: 'added_at',
  added_by: 'added_by'
};

exports.Prisma.DoorsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  status: 'status',
  added_at: 'added_at'
};

exports.Prisma.Face_devicesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  door_id: 'door_id',
  device_ip: 'device_ip',
  serial_number: 'serial_number',
  port: 'port',
  direction: 'direction',
  password: 'password',
  status: 'status',
  is_local: 'is_local',
  added_at: 'added_at',
  updated_at: 'updated_at'
};

exports.Prisma.Employee_door_tasksScalarFieldEnum = {
  id: 'id',
  employee_id: 'employee_id',
  door_id: 'door_id',
  action: 'action',
  status: 'status',
  retry_count: 'retry_count',
  error: 'error',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.GatesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  branch_id: 'branch_id',
  telegram_chat_ids: 'telegram_chat_ids',
  status: 'status',
  added_at: 'added_at',
  updated_at: 'updated_at'
};

exports.Prisma.Anpr_camerasScalarFieldEnum = {
  id: 'id',
  name: 'name',
  gate_id: 'gate_id',
  camera_ip: 'camera_ip',
  mac_address: 'mac_address',
  port: 'port',
  direction: 'direction',
  username: 'username',
  password: 'password',
  status: 'status',
  added_at: 'added_at',
  updated_at: 'updated_at'
};

exports.Prisma.Vehicle_passesScalarFieldEnum = {
  id: 'id',
  branch_id: 'branch_id',
  gate_id: 'gate_id',
  camera_id: 'camera_id',
  plate_number: 'plate_number',
  direction: 'direction',
  photo: 'photo',
  date: 'date',
  created_at: 'created_at'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};


exports.Prisma.ModelName = {
  branches: 'branches',
  departments: 'departments',
  employment_orders: 'employment_orders',
  employees: 'employees',
  face_passes: 'face_passes',
  holidays: 'holidays',
  positions: 'positions',
  sessions: 'sessions',
  telegram_bots: 'telegram_bots',
  time_off: 'time_off',
  timesheet: 'timesheet',
  users: 'users',
  menus: 'menus',
  user_menu_access: 'user_menu_access',
  work_schedules: 'work_schedules',
  employee_schedule_history: 'employee_schedule_history',
  doors: 'doors',
  face_devices: 'face_devices',
  employee_door_tasks: 'employee_door_tasks',
  gates: 'gates',
  anpr_cameras: 'anpr_cameras',
  vehicle_passes: 'vehicle_passes'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
